package models.book;

public enum Genre {
    SCIENCE_FICTION,
    MAGICAL_REALISM,
    HIGH_FANTASY,
    FANTASY_FICTION,
    CONTEMPORARY_FANTASY,
    YOUNG_ADULT_FICTION,
    NOVEL,
    HISTORICAL_FICTION,
    HISTORICAL_NOVEL,
    ROMANCE_NOVEL,
    SATIRE,
    NOVEL_OF_MANNERS,
    REGENCY_ROMANCE,
    DOMESTIC_FICTION,
    BILDUNGSROMAN,
    MYSTERY,
    THRILLER,
    SUSPENSE,
    PSYCHOLOGICAL_FICTION,
    SOCIAL_SCIENCE_FICTION,
    POLITICAL_FICTION,
    EPIC,
    ADVENTURE_FICTION,
    NAUTICAL_FICTION
}
